resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/24.yaml

packages:
- .

extra-deps:
- git: git@github.com:fmidue/IOTasks.git
  commit: ddec953443a6af839bcce2c29f7664ca40e6167c
- git: https://github.com/owestphal/type-match
  commit: e1afab43d2e8bfa5e2006492ed34060036e7be51
- git: https://github.com/IagoAbal/haskell-z3
  commit: 6368e451e45359563106da7e917f6594453c5161
